[D1] HistoryView와 ResultView를 연결했습니다.
DeveloperAcademy-POSTECH/MacC-Team-IKU pull request #101
Opened 2022-11-23 16:12 UTC by moonjs0113

# 이슈번호
🔐 close #92 
🔐 close #97
🔐 close #98 
🔐 close #99 
🔐 close #100 
🔐 close #102  
🔐 close #103  

# 내용
- 녹화 시 불필요한 녹음을 하지 않습니다.
    - 마이크 권한을 받지 않습니다.
- 검사 결과 View의 UI가 업데이트 되었습니다.
- 달력에서 List 버튼을 누르면 List View 나타납니다.

2022-11-24 00:08 UTC, sustainable-git requested changes
필요 없는 마이크가 없어졌다니 좋군요!
plist 수정 바랍니다!

2022-11-24 00:18 UTC, GroundDev approved these changes

2022-11-24 00:37 UTC, moonjs0113 commented
@sustainable-git 
plist 수정되었습니다!

2022-11-24 01:58 UTC, wonny1012 approved these changes

2022-11-25 01:33 UTC, sustainable-git approved these changes

2022-11-25 01:35 UTC, sustainable-git requested changes
merge conflict가 해결되지 않았습니다.

2022-11-25 01:35 UTC, sustainable-git commented on IKU/IKU/Views/ResultViewController.swift
> +        fetchUI()
p1)

수정이 덜 되었습니다.

2022-11-25 01:35 UTC, sustainable-git commented on IKU/IKU/Views/ResultViewController.swift
> +>>>>>>> Rey/ListButtonRebase
p1)

확인 부탁드려요

2022-11-25 03:09 UTC, sustainable-git approved these changes

2022-11-25 03:09 UTC, merged