[D0] 영어버전+탭바수정+결과뷰UI수정
DeveloperAcademy-POSTECH/MacC-Team-IKU pull request #127
Opened 2022-11-26 15:14 UTC by wonny1012

# 이슈번호
🔓 open #125 #126 

# 내용
* 영어버전(첫 화면제외)
* 탭바수정 
Dictionary 삭제
* 결과뷰UI 수정
영문버전이 들어가면서 글자수가 변경되어 조금씩 수정이 들어갔습니다.
월요일날 리비에게 다시 컴펌 받을 예정입니다.

2022-11-26 15:57 UTC, sustainable-git requested changes
주말에도 수고가 많으십니다.
몇몇 부분 확인 부탁드릴게요!

2022-11-26 15:57 UTC, sustainable-git commented on IKU/IKU/Data/TestGuideString.swift
> +        case .coverTo(let eye): return "Recording covering your eyes \n Cover your \(eye == .left ? "Right" : "Left")Eye"
p2)

voice text인데, 특수문자까지 그대로 읽을 것 같은 느낌이 듭니다.
확인 부탁드려요

2022-11-26 15:57 UTC, sustainable-git commented on IKU/IKU/Views/ResultViewController.swift
> +            resultmemoLabel.text = "There is something wrong with eyes. \nPlease visit an hospital as soon as possible \nfor accurate test"
p3)

개행(\n) 없이 만드는게 더 좋지 않을까 합니다. Device에 따라 4줄, 5줄 글자가 생기면 보기 어려울 것 같아요.
현재 이 View에 ScrollView가 포함되어 있지 않기 때문에 더더욱 개행을 줄여야 할 것 같습니다.

2022-11-26 15:57 UTC, sustainable-git commented on IKU/IKU/App/Info.plist
> -	<string>사시각 측정을 위해 카메라 권한이 필요합니다.</string>
👏

2022-11-26 16:28 UTC, wonny1012 commented on IKU/IKU/Views/ResultViewController.swift
> +            resultmemoLabel.text = "There is something wrong with eyes. \nPlease visit an hospital as soon as possible \nfor accurate test"
읽는데 불편함이 있을까봐 마디마다 띄어쓰기를 한게 있습니다. 스크롤은 모든 뷰에 들어가기로 했던거 같은데 이부분에는 안들어갈까요??

2022-11-26 16:31 UTC, wonny1012 commented on IKU/IKU/Data/TestGuideString.swift
> +        case .coverTo(let eye): return "Recording covering your eyes \n Cover your \(eye == .left ? "Right" : "Left")Eye"
23번째 줄에서 left/right부분에서 버벅거림이 있고 \n 부분은 읽지 않고 있어요! 저 부분은 어떻게 해야할지 몰라 일단 놔두었습니다! 
레이 소환해서 물어볼 예정이에요!

2022-11-26 20:57 UTC, wonny1012 commented on IKU/IKU/Views/ResultViewController.swift
> +            resultmemoLabel.text = "There is something wrong with eyes. \nPlease visit an hospital as soon as possible \nfor accurate test"
문장단위로 띄어쓰기 하는걸로 변경했습니다!

2022-11-27 01:31 UTC, sunchoi22 approved these changes
워니 이거 말씀하신거 맞나요? 수고가 많습니다!! 
UI뷰는 영문판 화요일에 나오면 완벽하게 진행하는 것으로 알고 있겠습니다.
주말에도 열일하는 우리 아이쿠 멋져요!!!

2022-11-27 03:11 UTC, sustainable-git approved these changes

2022-11-27 03:14 UTC, merged