[D2] Complete HistoryView UI
DeveloperAcademy-POSTECH/MacC-Team-IKU pull request #16
Opened 2022-11-13 23:54 UTC by moonjs0113

# 이슈번호
🔓 open #6 

# 내용
- HistoryView UI 요소의 배치를 끝냈습니다.
- Scroll View 기능은 아직 적용되지 않았습니다.
    - UI가 전체적으로 확정되면 적용시키겠습니다.

# 스크린샷(Optional)
<img src="https://user-images.githubusercontent.com/47404421/201551223-a1b4f39d-a227-41e5-b309-767e1417b847.png" width="250"/>

2022-11-13 23:58 UTC, moonjs0113 commented on IKU/IKU/Data/StrabismusLog.swift
> +struct StrabismusLog: Hashable {
사시각 데이터의 구조가 확정되지 않아서 임시로 만든 데이터 입니다.

2022-11-13 23:58 UTC, moonjs0113 commented on IKU/IKU/Data/StrabismusLog.swift
> +    static var preview: StrabismusLog {
단일 목업데이터입니다.

2022-11-13 23:58 UTC, moonjs0113 commented on IKU/IKU/Data/StrabismusLog.swift
> +    static var previews: [StrabismusLog] {
복수 목업데이터입니다.

2022-11-14 00:00 UTC, moonjs0113 commented on IKU/IKU/Views/ViewModule/IKUChartView.swift
> +                    Chart {
사시각 데이터의 구조가 확정되면 Chart의 코드가 변경될 수 있습니다.

2022-11-14 00:45 UTC, sustainable-git requested changes
수고 많으셨습니다 :)

2022-11-14 00:45 UTC, sustainable-git commented on IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVMonth.swift
> +    }
p3)
calendarTitle이 suffix(3)이면 november일 때 ber로 나오나요?
prefix(3)이 아닐까요?

2022-11-14 00:45 UTC, sustainable-git commented on IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
> +        let min = currentYear - 50 - (currentYear - 2022)
p2)
currentYear - currentYear가 되어있어요!

2022-11-14 01:20 UTC, moonjs0113 commented on IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVMonth.swift
> +    }
@sustainable-git
놀랍게도 사용되지 않은 변수라 삭제했습니다.

2022-11-14 01:20 UTC, moonjs0113 commented on IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
> +        let min = currentYear - 50 - (currentYear - 2022)
수정되었습니다. :)

2022-11-14 06:53 UTC, sustainable-git approved these changes
멋져요!

2022-11-14 08:18 UTC, wonny1012 approved these changes
수고하셨습니다.
1:1 과외 덕분에 self마스터가 되었습니다. 😃
여러분 이제 self가 궁금하시면 저에게 오십시요, (내가 틀리면 스승탓..?)
IKUCalendarView는 잠시 흐린눈 하겠습니다...

2022-11-15 00:31 UTC, merged

2022-11-15 04:23 UTC, GroundDev approved these changes
늦게 리뷰해서 미안합니다 레이
수고하셨습니다!

2022-11-15 04:23 UTC, GroundDev commented on IKU/IKU/Data/StrabismusLog.swift
> +            StrabismusLog(date: .now.addingTimeInterval(.init(integerLiteral: $0)), degree: Double.random(in: 1...20))
## P5
### 맵이란(from 야곰 스위프트 프로그래밍)
스위프트는 함수를 일급 객체로 취급합니다. 따라서 함수를 다른 함수의 전달인자로 사용할 수 있습니다. 이렇게 매개변수로 함수를 갖는 함수를 고차함수라고 하는데, 스위프트의 대표적인 고차함수 중 맵이 있습니다.
- 맵은 자신을 호출할 때 매개변수로 전달된 함수를 실행하여 그 결과를 다시 반환해주는 함수입니다.
- 맵을 사용하면 컨테이너가 담고 있던 각각의 값을 매개변수를 통해 받은 함수에 적용한 후 다시 컨테이너에 포장하여 반환합니다. 기존 컨테이너의 값은 변경되지 않고 새로운 컨테이너가 생성되어 반환됩니다. 그래서 맵은 기존 데이터를 변형하는데에 많이 사용됩니다.

그렇다면 현재 map은 어떤 함수를 매개변수를 통해 받은걸까요?
`{ StrabismusLog(date: .now.addingTimeInterval(.init(integerLiteral: $0)), degree: Double.random(in: 1...20)) }` 이라는 `() -> StrabismusLog`인 클로져입니다.
`(0...10)`은 ClosedRange라는 타입입니다(struct입니다). 0부터 10까지의 숫자가 있는 녀석인데, 이 녀석의 각 요소에 map 메서드의 전달인자로 전달한 클로져(위의 클로져)를 적용해줍니다. 그 결과는? `[StrabismusLog]`이겠네요.
참고로 `$0`는 매개변수와 반환 타입을 생략하여 간략화하기 위해 쓰였습니다. 그리고 `map( { } )`에서 후행 클로저를 사용한 것으로 되어 `map { }`의 형태가 되었죠.

2022-11-15 04:23 UTC, GroundDev commented on IKU/IKU/Resource/Color.xcassets/ikuBackground.colorset/Contents.json
> +        "color-space" : "srgb",
## P5
색을 표현하는 방법으로 여러가지 방법이 있는데, 그 중 [DisplayP3모델](https://developer.apple.com/documentation/coregraphics/cgcolorspace/1408916-displayp3)에서 [sRGB모델](https://developer.apple.com/documentation/appkit/nscolorspace/1412071-srgb)로 [변경한 것으로 보입니다.](https://eeyatho.tistory.com/153)
이는 이 이후의 다른 색상에도 동일하게 적용되었습니다.