[D2] CoverTestView UI 완성 및 SelectPhotoView 연결
DeveloperAcademy-POSTECH/MacC-Team-IKU pull request #50
Opened 2022-11-18 00:27 UTC by moonjs0113

# 이슈번호
🔐 close #23 #25 #26 #27 #28 #29 #31 #32 #55

# 내용
- CoverTestView UI 완성했습니다.
- 검사가 끝나면 SelectPhotoView로 넘어갑니다.

# 테스트 방법(Optional)
- 검사하기를 통해 실제 녹화를 진행해보시면 됩니다.

2022-11-18 01:30 UTC, GroundDev approved these changes
선 Approve합니다. 수고하셨습니다 레이!

2022-11-20 05:42 UTC, sustainable-git requested changes
감사합니다.

2022-11-20 05:42 UTC, sustainable-git commented on IKU/IKU/Views/CoverTestViewModel.swift
> +    lazy var sceneView: ARSCNView = {
p2)

ViewModel이 View를 가지고 있으면 ViewModel이 아니라고 생각합니다.
View를 가지게 되면 ViewModel에서 UITest가 어렵습니다. [다른 예시 : stackoverflow](https://stackoverflow.com/questions/3670629/should-a-viewmodel-in-mvvm-reference-the-view)
delegate는 ViewController에서 session.delegate = viewModel로 넘겨주는 방식으로 변경하면 어떨까요?

2022-11-20 05:42 UTC, sustainable-git commented on IKU/IKU/Views/SelectPhotoViewController.swift
> +//        guard let movieURL = Bundle.main.url(forResource: "video", withExtension: "m4v") else { return }
p3)

제가 썼던 코드인데요,
이런 코드 더 이상 안쓰니 삭제 부탁드립니닷 하하
(에셋도 삭제해주시면 무한한 감사...)

2022-11-20 05:42 UTC, sustainable-git commented on IKU/IKU/Views/SelectPhotoViewController.swift
> +    func prepareURL(url: URL) {
p2)

현재 이 함수는 아무도 부르고 있지 않아 보입니다.
직전 View로 부터 url을 받지 않고 이 View로 넘어올 수 없도록, init()을 만들어서 작업하면 어떨까요?
convenience init을 제안합니다.
```suggestion
    convenience init(withVideoURL url: URL)
```

2022-11-20 10:33 UTC, moonjs0113 commented on IKU/IKU/Views/SelectPhotoViewController.swift
> +    func prepareURL(url: URL) {
@sustainable-git
이전 VC에서 SelectPhotoViewController를 생성 후 [호출](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-IKU/pull/50/files#diff-54004a3a41893a06134decf7651752be61f9a8c9eba26dc5de96a2c66a50088fR228)하고 있기는 합니다!

2022-11-21 01:09 UTC, sustainable-git approved these changes

2022-11-21 01:51 UTC, merged