[D3] StoryView에서 눈 선택하는 로직 구현
DeveloperAcademy-POSTECH/MacC-Team-IKU pull request #51
Opened 2022-11-18 01:15 UTC by GroundDev

# 이슈번호
🔓 open #32
🔓 open #41

# 내용
StoryView 내에서 왼쪽 눈, 오른쪽 눈을 선택하는 로직을 구현했습니다.
일반적인 Segmented Control을 이용하는 것이 아니라, 내부에 이미지도 들어가고 텍스트도 들어가는 등 커스텀할 부분이 많습니다.
이에 관련해서 리서치 하던 중 [본 작업의 목적에 부합하는 글을 찾았습니다.](https://softwarecountry.com/company/our-blog/custom-segmented-control-swiftui/)
이에 적극적으로 코드를 사용하였습니다.
- 다만, 어렴풋이 이해하고 있을 뿐 아직 코드에 대해 다 이해하지는 못했습니다.
- 또한 리비에게 확인해보니 아직 그림이 확정이 되지 않았습니다. 이에 로직 구현만 완료하고 margin값 등은 신경쓰지 않았습니다.

# 테스트 방법(Optional)
main으로 merge하고 난 이후에는 #33 에서 다룬것과 같은 방식으로 test를 해볼 수 있습니다.
왼쪽, 오른쪽 그림을 누르시면 사용자가 어떤 눈을 선택했는지에 관한 정보는 `StoryView.swift`내의 `selectedEye` 변수가 갖고 있습니다(source of truth이기도 함). 이를 확인하기 위해 선택하는 부분 아래에 Text의 형식으로 나타나게끔 했습니다.

# 스크린샷(Optional)
![Simulator Screen Shot - iPhone 13 - 2022-11-18 at 10 06 27](https://user-images.githubusercontent.com/103012763/202592980-4003e47a-9d45-4c24-9565-7cb70c73a574.png)

2022-11-18 01:25 UTC, GroundDev reviewed
코드리뷰 중간 중간에 등장하는 `TODO`는 제 개인 메모입니다. 확인하지 않으셔도 됩니다.

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Resource/Assets.xcassets/lefteye.imageset/Contents.json
> +      "filename" : "lefteye.png",
## P5
왼쪽 눈 사진, 오른쪽 눈 사진은 피그마에서 임시로 누끼를 따서 생성하였습니다. 그림이 확정되면 교체할 예정입니다.

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +}
## P5
다른 곳에서도 접근할 수도 있기에 우선 전역으로 enum을 선언했습니다. 전역으로 하지 않고 하는 방법이 있는지 고민해보겠습니다. rawValue값을 설정한 이유는 단순 디버깅 용도입니다. 추후 삭제해도 로직 작동에는 전혀 영향이 없습니다.

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/StoryView.swift
> +    static let ikuEyeSelectBackground: Color = Color("ikuEyeSelectBackground")
## P5
특정 눈을 선택하지 않았을 때의 배경색입니다.

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/StoryView.swift
> +    @State private var selectedEye: Eyes = .left
## P5
선택된 눈이 왼쪽인지 오른쪽인지 저장하는 용도의 변수입니다. 기본값은 왼쪽입니다.

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/StoryView.swift
> +                SelectWhichEyeView(selectedEye: $selectedEye)
## P5
눈 선택하는 View의 코드가 길어질 것 같아 따로 분리하였습니다.

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/StoryView.swift
> +                    .padding()
## P5
주석에도 나와있듯이, UI적으로 디버깅이 되는지 확인하기 위해 작성한 코드이므로 삭제해도 무방합니다.

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +public struct CustomPicker<SelectionValue, Content> : View where SelectionValue : Hashable, Content : View {
## P5
로직이 어떻게 작동된다는 것인지 전부 이해하진 못했습니다. 추후 좀 더 살펴보겠습니다.

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +        self.content = content()
## P5
`// TODO: - 이 부분 이해하기`

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +        .environment(\.selectedSegmentTag, $selection)
## P5
`// TODO: - environment 더 깊이있게 이해하기`

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +                Image("righteye").segmentedControlItemTag(Eyes.right)
## P5
`// TODO: - 애플 프레임워크에서 제공하는 Picker에서의 tag의 용도 이해하기`

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +    @ViewBuilder var body: some View {
## P5
`// TODO: - ViewBuilder 개념 다시 살펴보기`

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +        set { self[SelectedSegmentTagKey.self] = newValue }
## P5
`// TODO: - 배열의 형태로 되어 있는 이유를 이해하기`

2022-11-18 01:25 UTC, GroundDev commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +    static var defaultValue: Any?
## P5
`// TODO: - Any이자 옵셔널로 타입을 선언한 이유에 대해 이해하기`

2022-11-18 07:42 UTC, moonjs0113 approved these changes

2022-11-19 12:27 UTC, wonny1012 approved these changes
수고하셨습니다 땅님~

2022-11-20 05:43 UTC, sustainable-git commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +}
p2)

이건 이번 pull request에서 빼놓을 수 있을까요?

2022-11-20 05:48 UTC, sustainable-git requested changes
수고하셨습니다. 디자인이 변경되었다 보니, 수정 사항이 또 발생하겠네요 ㅠㅠ

2022-11-20 05:48 UTC, sustainable-git commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +    @ViewBuilder var body: some View {
p5)

@ViewBuilder 없이 동작하지 않나요?

2022-11-20 05:48 UTC, sustainable-git commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +        self.content = content()
p5)

SwiftUI에서 함수가 View를 만든다면 반드시 `@ViewBuilder` annotation을 붙여야 합니다.

2022-11-21 01:10 UTC, GroundDev commented on IKU/IKU/Views/SelectWhichEyeView.swift
> +    @ViewBuilder var body: some View {
맞습니다!

2022-11-21 01:27 UTC, sustainable-git approved these changes

2022-11-21 01:29 UTC, merged