[D2] Connect ViewController
DeveloperAcademy-POSTECH/MacC-Team-IKU pull request #59
Opened 2022-11-18 03:41 UTC by moonjs0113

# 이슈번호
🔐 close #56
🔐 close #58

# 내용
- HistoryView -> CoverTestView -> SelectPhotoView -> ResultView 를 연결하였습니다.
- AR 화면에서 가져올 수 있는 값을 0.1 초 단위로 저장합니다.
    - SelectPhotoView에서 선택한 시간으로 인덱싱하여 값을 사용하게 됩니다.

2022-11-18 11:05 UTC, GroundDev approved these changes
선 Approve 후 코드리뷰하겠습니다. 수고하셨습니다 레이!

2022-11-18 11:05 UTC, GroundDev commented on IKU/IKU/Data/Eyes.swift
> +}
## P5
드디어 많고 많은 Eyes들을 하나로 정리했군요!

2022-11-20 05:53 UTC, sustainable-git requested changes
엄청난 작업이군요!

2022-11-20 05:53 UTC, sustainable-git commented on IKU/IKU/Data/Eyes.swift
> +}
p2)

이거 이미 `Eye.swift`로 만들고 머지돼있어서 없애주실 수 있나요?

2022-11-20 05:53 UTC, sustainable-git commented on IKU/IKU/Extension/UIView+Extension.swift
> +    }
p5)

멋져 컴바인... 👏

2022-11-20 23:56 UTC, sustainable-git approved these changes

2022-11-21 00:08 UTC, merged