[D2] CVCalendar Library 파일 추가
DeveloperAcademy-POSTECH/MacC-Team-IKU pull request #9
Opened 2022-11-10 16:48 UTC by moonjs0113

# 이슈번호
🔓 open #6

# 내용
- Calendar 개발을 위한 [CVCalendar](https://github.com/CVCalendar/CVCalendar) Library를 추가하였습니다.
    - Cocoapods을 이용하는 방법이 있었지만, 그럴 경우 라이브러리를 수정할 수 없기 때문에 직접 파일을 추가하였습니다.
    - 해당 라이브러리를 기반으로 `IKUCalendaView`를 생성할 예정입니다.

2022-11-11 07:28 UTC, sustainable-git requested changes
Calendar 고민하시느라 수고가 많으셨습니다.
혹시 License 확인 부탁드려도 될까요?

2022-11-11 07:28 UTC, sustainable-git commented on IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
> +    var calendarView: CVCalendarView!
p3

forced unwrapping은 최소화 하는게 좋지 않을까요?
init에서 따로 쓰지 않아도 좋을것 같아요

```suggestion
   var calendarView: CVCalendarView = CVCalendarView()
```

2022-11-11 08:53 UTC, moonjs0113 commented on IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
> +    var calendarView: CVCalendarView!
[CocoaPods CVCalendar](https://cocoapods.org/pods/CVCalendar)
MIT License입니다!

2022-11-11 08:57 UTC, moonjs0113 commented on IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
> +    var calendarView: CVCalendarView!
@sustainable-git 
P3 사항 반영되었습니다!

2022-11-12 06:32 UTC, sustainable-git approved these changes

2022-11-12 08:31 UTC, wonny1012 approved these changes
LGTM~

2022-11-12 11:48 UTC, merged

2022-11-14 08:48 UTC, GroundDev reviewed
수고하셨습니다 레이!

2022-11-14 08:48 UTC, GroundDev commented on IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
> +    }
## P5
`required init()`은 하위클래스에서 `super.init()`의 형태로 초기화할 수 있는게 아니라 [직접 구현해야만하는 메소드입니다.](https://ios-development.tistory.com/44)