[D1] TextField구현
DeveloperAcademy-POSTECH/MacC-Team-IKU pull request #91
Opened 2022-11-22 14:49 UTC by wonny1012

# 이슈번호
🔐 close # 87

# 내용
닉네임, 나이, 병원즐겨찾기 모두 입력값을 받을 수 있게 했습니다.
나이는 0~99세로 제한을 주는게 아닌 정수값을 받을 수 있게했습니다. 
나머지 구현된것들은 이슈당 한개씩 올리겠습니다. 

# 테스트 방법
SceneDelegate에서
let testVC = UINavigationController(rootViewController: ProfileViewController())
로 바꿔서 확인하시면 됩니다.

2022-11-22 15:29 UTC, moonjs0113 commented on IKU/IKU/Views/ProfileViewController.swift
> +    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
[P5] return 키 입력시에 키보드가 내려가지 않는데, 아직 사용하지 않은 함수인가요?

2022-11-22 15:39 UTC, wonny1012 commented on IKU/IKU/Views/ProfileViewController.swift
> +    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
이거 작동하지 않는 부분이라 TextField구현수정 커밋에 보시면 사라져 있습니다.

2022-11-22 15:42 UTC, moonjs0113 commented on IKU/IKU/Views/ProfileViewController.swift
> +        tf.keyboardType = .numberPad
[P3] 다른 UI Property에 대한 속성을 전부 setup에서 저장하고 있기에 `age: UITextField`에 대한 속성 저장도 [`setup()`](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-IKU/pull/91/files#diff-b7328e36fea14ae4fb285358f0d07c674a6019c39e18e8a6ef88f441708943e6R80)에서 하는 것이 좋다고 생각합니다.

2022-11-22 15:45 UTC, wonny1012 commented on IKU/IKU/Views/ProfileViewController.swift
> +        nickName.text = " "
수정했습니다.

2022-11-22 22:15 UTC, GroundDev approved these changes

2022-11-23 14:38 UTC, sustainable-git requested changes

2022-11-23 14:38 UTC, sustainable-git commented on IKU/IKU/Views/ProfileViewController.swift
> +    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
p2)

아직 안사라진것 같아요!

2022-11-24 01:30 UTC, sustainable-git approved these changes

2022-11-24 01:51 UTC, merged