[D1] 닉네임 글자수 제한
DeveloperAcademy-POSTECH/MacC-Team-IKU pull request #94
Opened 2022-11-22 15:43 UTC by wonny1012

# 이슈번호
🔓 open #88 

# 내용
프로필 화면에서 닉네임 글자수 제한을 뒀습니다,
7글자인줄 알고 커밋할때 limitLength = 7로 두었는데 10으로 두고 바로 다시 커밋 날리겠습니다.

2022-11-22 22:15 UTC, GroundDev approved these changes

2022-11-23 14:32 UTC, sustainable-git requested changes
키보드 내리는거 찾느라 고생하셨습니다 :)

2022-11-23 14:32 UTC, sustainable-git commented on IKU/IKU/Views/StoryView.swift
> +import UIKit
p2)

여기서 UIKit이 들어가야 할 이유가 없어 보입니다.

2022-11-23 14:32 UTC, sustainable-git commented on IKU/IKU/Views/StoryView.swift
> +//                    })
p3)

이 부분은 삭제해야하는 부분일까요?

2022-11-24 01:32 UTC, sustainable-git approved these changes

2022-11-24 01:52 UTC, merged